import { StrictMode, FormEvent, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'

type Risk={level:'low'|'medium'|'high';label:string;score:number;reasons:string[]}
type Dashboard={planned_value:number;executed_value:number;execution_rate:number;demands:number;altered_demands:number;risk_demands:number;medium_risk_demands:number;extraordinary_inclusions:number;cancelled:number;reprogrammed:number;status_distribution:Record<string,number>;notice:string}
type Demand={id:number;code:string;title:string;unit:string;category:string;status:string;execution_status:string;desired_date:string;original_value:number;revised_value:number|null;adjusted_value:number|null;executed_value:number;version:number;sei_process_number:string|null;sei_status:string;pncp_item_code:string|null;extraordinary:boolean;risk:Risk}
type Integration={id:string;name:string;protocol:string;status:string;configured:boolean;transmission_enabled:boolean;requirements:string[];notice:string}
type Audit={id:number;demand_code:string;action:string;actor_role:string;detail:string;created_at:string}
type Detail=Demand&{risk:Risk}
type Version={version:number;reason:string;created_at:string}
type Pncp={valid:boolean;publishable:boolean;notice:string;errors:string[]}
type Backplan={non_normative_notice:string;milestones:{name:string;date:string}[]}
type Tab='executive'|'portfolio'|'integrations'|'audit'

const currency=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n)
const date=(value:string)=>new Intl.DateTimeFormat('pt-BR').format(new Date(`${value.slice(0,10)}T12:00:00`))
const labels:Record<string,string>={not_started:'Não iniciada',preparatory:'Fase preparatória',contracting:'Em contratação',contracted:'Contratada',reprogrammed:'Reprogramada',cancelled:'Cancelada',goods:'Bens',services:'Serviços',works:'Obras',it:'Tecnologia',seed_created:'Carga demonstrativa',demand_created:'Demanda criada',execution_transition:'Mudança de execução',sei_process_linked:'Vínculo SEI',approved_review_applied:'Revisão aprovada',post_loa_adjustment:'Adequação pós-LOA'}
const next:Record<string,string|undefined>={not_started:'preparatory',preparatory:'contracting',contracting:'contracted',reprogrammed:'preparatory'}
const api=async<T,>(url:string,options?:RequestInit):Promise<T>=>{const response=await fetch(url,options);if(!response.ok)throw new Error((await response.json().catch(()=>null))?.detail||'Não foi possível concluir a operação.');return response.json()}

function App(){
 const [tab,setTab]=useState<Tab>('executive'); const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [demands,setDemands]=useState<Demand[]>([]); const [integrations,setIntegrations]=useState<Integration[]>([]); const [audits,setAudits]=useState<Audit[]>([]); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [showForm,setShowForm]=useState(false); const [detail,setDetail]=useState<Detail|null>(null); const [versions,setVersions]=useState<Version[]>([]); const [pncp,setPncp]=useState<Pncp|null>(null); const [plan,setPlan]=useState<Backplan|null>(null); const [seiTarget,setSeiTarget]=useState<Demand|null>(null); const [seiNumber,setSeiNumber]=useState('')
 const load=async()=>{try{setError('');const[d,items,ints,events]=await Promise.all([api<Dashboard>('/api/governance/dashboard'),api<Demand[]>('/api/demands'),api<Integration[]>('/api/integrations'),api<Audit[]>('/api/audit-events?limit=30')]);setDashboard(d);setDemands(items);setIntegrations(ints);setAudits(events)}catch(e){setError(e instanceof Error?e.message:'Falha inesperada')}}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>demands.filter(d=>(status==='all'||d.execution_status===status)&&`${d.code} ${d.title} ${d.unit}`.toLowerCase().includes(query.toLowerCase())),[demands,query,status])
 const openDetail=async(d:Demand)=>{try{const[item,history,payload,back]=await Promise.all([api<Detail>(`/api/demands/${d.id}`),api<Version[]>(`/api/demands/${d.id}/versions`),api<Pncp>(`/api/demands/${d.id}/pncp-payload`),api<Backplan>('/api/backplanning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({desired_date:d.desired_date,category:d.category})})]);setDetail(item);setVersions(history);setPncp(payload);setPlan(back)}catch(e){setError(e instanceof Error?e.message:'Falha ao abrir demanda')}}
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);try{await api('/api/demands',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:form.get('title'),unit:form.get('unit'),category:form.get('category'),desired_date:form.get('desired_date'),original_value:Number(form.get('original_value')),pncp_item_code:form.get('pncp_item_code')||null})});setMessage('Demanda criada com histórico e auditoria.');setShowForm(false);e.currentTarget.reset();await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao criar demanda')}}
 const advance=async(d:Demand)=>{const target=next[d.execution_status];if(!target)return;try{await api(`/api/demands/${d.id}/execution-transition`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target})});setMessage(`Demanda ${d.code} avançou para ${labels[target]}.`);await load()}catch(e){setError(e instanceof Error?e.message:'Falha na transição')}}
 const linkSei=async(e:FormEvent)=>{e.preventDefault();if(!seiTarget)return;try{await api(`/api/demands/${seiTarget.id}/sei-link`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({process_number:seiNumber})});setMessage(`Processo SEI vinculado à demanda ${seiTarget.code}.`);setSeiTarget(null);setSeiNumber('');await load()}catch(e){setError(e instanceof Error?e.message:'Número SEI inválido')}}
 return <div className="shell"><aside><div className="brand"><span>MP</span><div><b>PAC Digital</b><small>MPRJ · v0.8</small></div></div><nav><Nav active={tab==='executive'} onClick={()=>setTab('executive')} icon="◫">Visão executiva</Nav><Nav active={tab==='portfolio'} onClick={()=>setTab('portfolio')} icon="≡">Carteira do PAC</Nav><Nav active={tab==='integrations'} onClick={()=>setTab('integrations')} icon="↔">Integrações</Nav><Nav active={tab==='audit'} onClick={()=>setTab('audit')} icon="✓">Governança</Nav></nav><div className="side-note"><span className="pulse"/>Ambiente demonstrativo<small>Somente dados fictícios</small></div></aside><main><header><div><span className="eyebrow">PLANO ANUAL DE CONTRATAÇÕES</span><h1>{tab==='executive'?'Visão executiva':tab==='portfolio'?'Carteira de demandas':tab==='integrations'?'Interoperabilidade':'Governança e auditoria'}</h1><p>{tab==='executive'?'Decisão orientada por execução, risco e rastreabilidade.':tab==='portfolio'?'Planejamento e acompanhamento em uma única carteira.':tab==='integrations'?'Arquitetura preparada para SEI!, PNCP e identidade institucional.':'Histórico preservado e eventos rastreáveis.'}</p></div><div className="header-actions"><span className="period">Exercício 2026</span><button onClick={()=>{setTab('portfolio');setShowForm(true)}}>+ Nova demanda</button></div></header>{error&&<Alert kind="error" text={error} close={()=>setError('')}/>} {message&&<Alert kind="success" text={message} close={()=>setMessage('')}/>} {tab==='executive'&&dashboard&&<Executive dashboard={dashboard} demands={demands} open={d=>void openDetail(d)}/>} {tab==='portfolio'&&<Portfolio demands={filtered} query={query} setQuery={setQuery} status={status} setStatus={setStatus} showForm={showForm} setShowForm={setShowForm} create={create} advance={advance} open={d=>void openDetail(d)} sei={setSeiTarget}/>} {tab==='integrations'&&<Integrations items={integrations}/>} {tab==='audit'&&<Governance audits={audits} demands={demands}/>}</main>{detail&&<DemandDrawer demand={detail} versions={versions} pncp={pncp} plan={plan} close={()=>setDetail(null)}/>} {seiTarget&&<Modal title="Vincular processo SEI" close={()=>setSeiTarget(null)}><p><b>{seiTarget.code}</b> — {seiTarget.title}</p><form onSubmit={linkSei}><label>Número do processo<input autoFocus required placeholder="20.22.0001.0000000.2027-00" value={seiNumber} onChange={e=>setSeiNumber(e.target.value)}/></label><p className="fineprint">O vínculo é local. A comunicação automática permanece bloqueada até autorização do SEI-MPRJ.</p><div className="modal-actions"><button type="button" className="ghost" onClick={()=>setSeiTarget(null)}>Cancelar</button><button type="submit">Vincular processo</button></div></form></Modal>}</div>
}

function Executive({dashboard:d,demands,open}:{dashboard:Dashboard;demands:Demand[];open:(d:Demand)=>void}){const statuses=Object.entries(d.status_distribution);const max=Math.max(...statuses.map(([,v])=>v),1);return <><section className="hero-cards"><Metric label="Planejado" value={currency(d.planned_value)} hint={`${d.demands} demandas no exercício`} tone="navy"/><Metric label="Executado" value={currency(d.executed_value)} hint={`${d.execution_rate}% do valor planejado`} tone="green" progress={d.execution_rate}/><Metric label="Risco alto" value={String(d.risk_demands)} hint={`${d.medium_risk_demands} com risco médio`} tone="amber"/><Metric label="Alterações" value={String(d.altered_demands)} hint="demandas versionadas" tone="blue"/></section><section className="grid-two"><article className="panel"><div className="panel-title"><div><span className="kicker">EXECUÇÃO</span><h2>Distribuição da carteira</h2></div><span className="badge">Atualizado agora</span></div><div className="bars">{statuses.map(([key,value])=><div className="bar-row" key={key}><span>{labels[key]||key}</span><div><i style={{width:`${value/max*100}%`}}/></div><b>{value}</b></div>)}</div></article><article className="panel"><div className="panel-title"><div><span className="kicker">GOVERNANÇA</span><h2>Movimentações críticas</h2></div></div><div className="signal-grid"><Signal value={d.extraordinary_inclusions} label="Inclusões extraordinárias"/><Signal value={d.reprogrammed} label="Reprogramações"/><Signal value={d.cancelled} label="Cancelamentos"/><Signal value={d.altered_demands} label="Demandas alteradas"/></div><p className="fineprint">{d.notice}</p></article></section><section className="panel"><div className="panel-title"><div><span className="kicker">ATENÇÃO DA GESTÃO</span><h2>Demandas prioritárias</h2></div></div><div className="priority-list">{demands.filter(x=>x.risk.level!=='low').slice(0,5).map(item=><button className="priority" key={item.id} onClick={()=>open(item)}><Risk risk={item.risk}/><span><b>{item.code} · {item.title}</b><small>{item.unit}</small></span><strong>{currency(item.adjusted_value??item.revised_value??item.original_value)}</strong><em>→</em></button>)}</div></section></>}
function Portfolio(p:{demands:Demand[];query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;showForm:boolean;setShowForm:(v:boolean)=>void;create:(e:FormEvent<HTMLFormElement>)=>void;advance:(d:Demand)=>void;open:(d:Demand)=>void;sei:(d:Demand)=>void}){return <>{p.showForm&&<form className="panel demand-form" onSubmit={p.create}><div className="panel-title"><div><span className="kicker">NOVA DEMANDA</span><h2>Registrar no planejamento</h2></div><button type="button" className="icon-button" onClick={()=>p.setShowForm(false)}>×</button></div><div className="form-grid"><label className="wide">Objeto<input required name="title" minLength={5}/></label><label>Unidade requisitante<input required name="unit" minLength={3}/></label><label>Categoria<select name="category"><option value="goods">Bens</option><option value="services">Serviços</option><option value="works">Obras</option><option value="it">Tecnologia</option></select></label><label>Data desejada<input required type="date" name="desired_date"/></label><label>Valor estimado<input required type="number" min="0.01" step="0.01" name="original_value"/></label><label>Código de catálogo PNCP<input name="pncp_item_code" placeholder="Opcional nesta etapa"/></label></div><div className="form-actions"><span>O primeiro registro histórico será criado automaticamente.</span><button type="submit">Salvar demanda</button></div></form>}<section className="panel"><div className="toolbar"><input aria-label="Buscar demandas" placeholder="Buscar por código, objeto ou unidade" value={p.query} onChange={e=>p.setQuery(e.target.value)}/><select aria-label="Filtrar situação" value={p.status} onChange={e=>p.setStatus(e.target.value)}><option value="all">Todas as situações</option>{Object.keys(next).concat(['contracted','cancelled']).map(x=><option value={x} key={x}>{labels[x]}</option>)}</select><div className="exports"><a href="/api/exports/demands.csv">CSV</a><a href="/api/exports/demands.xlsx">XLSX</a></div></div><div className="table-wrap"><table><thead><tr><th>Demanda</th><th>Unidade</th><th>Valor planejado</th><th>Situação</th><th>Risco</th><th>Integração</th><th/></tr></thead><tbody>{p.demands.map(d=><tr key={d.id}><td><button className="link-button" onClick={()=>p.open(d)}>{d.code}<small>{d.title} · v{d.version}</small></button></td><td>{d.unit}</td><td>{currency(d.adjusted_value??d.revised_value??d.original_value)}</td><td><Status value={d.execution_status}/></td><td><Risk risk={d.risk}/></td><td>{d.sei_process_number?<span className="integration-ok">SEI vinculado</span>:<button className="text-action" onClick={()=>p.sei(d)}>Vincular SEI</button>}</td><td>{next[d.execution_status]&&<button className="compact" onClick={()=>p.advance(d)}>Avançar</button>}</td></tr>)}</tbody></table></div><div className="table-footer">{p.demands.length} demanda(s) exibida(s)</div></section></>}
function Integrations({items}:{items:Integration[]}){return <><section className="integration-hero"><div><span className="kicker">ARQUITETURA INSTITUCIONAL</span><h2>Integração sem aprisionamento tecnológico</h2><p>Adaptadores isolam o domínio do PAC dos sistemas externos. Credenciais e transmissões permanecem desligadas até homologação.</p></div><div className="shield">✓<small>Transmissão<br/>bloqueada</small></div></section><section className="integration-grid">{items.map(item=><article className="panel integration-card" key={item.id}><div className={`integration-logo ${item.id}`}>{item.id==='sei'?'SEI':item.id==='pncp'?'PCA':'ID'}</div><div><span className={`connection ${item.status}`}>{item.status==='configured'?'Configurado':item.status==='staging'?'Preparado para configuração':'Planejado'}</span><h2>{item.name}</h2><p>{item.notice}</p><dl><div><dt>Protocolo</dt><dd>{item.protocol}</dd></div><div><dt>Transmissão</dt><dd>{item.transmission_enabled?'Ativa':'Desabilitada'}</dd></div></dl><h3>Dependências institucionais</h3><ul>{item.requirements.map(r=><li key={r}>{r}</li>)}</ul></div></article>)}</section><section className="notice"><b>Princípio de segurança</b><span>O sistema não contém credenciais, não publica no PNCP e não consome o SEI nesta versão. A ativação exige autorização, homologação e configuração externa.</span></section></>}
function Governance({audits,demands}:{audits:Audit[];demands:Demand[]}){return <section className="grid-governance"><article className="panel"><div className="panel-title"><div><span className="kicker">TRILHA IMUTÁVEL</span><h2>Eventos recentes</h2></div><span className="badge">{audits.length} registros</span></div><div className="timeline">{audits.map(a=><div key={a.id}><i/><time>{new Date(a.created_at).toLocaleString('pt-BR')}</time><b>{a.demand_code} · {labels[a.action]||a.action}</b><p>{a.detail}</p><small>Perfil: {a.actor_role}</small></div>)}</div></article><aside><article className="panel"><span className="kicker">CONTROLES</span><h2>Cobertura atual</h2><Check text="Versionamento de demandas"/><Check text="Justificativas obrigatórias"/><Check text="Registro de eventos"/><Check text="Separação planejamento × execução"/><Check text="Transmissões externas bloqueadas"/></article><article className="panel"><span className="kicker">QUALIDADE DOS DADOS</span><h2>{demands.filter(d=>d.pncp_item_code).length}/{demands.length}</h2><p>demandas com código de catálogo para pré-validação PNCP.</p></article></aside></section>}
function DemandDrawer({demand:d,versions,pncp,plan,close}:{demand:Detail;versions:Version[];pncp:Pncp|null;plan:Backplan|null;close:()=>void}){return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><aside className="drawer"><div className="drawer-head"><div><span className="kicker">{d.code} · VERSÃO {d.version}</span><h2>{d.title}</h2><p>{d.unit}</p></div><button className="icon-button" onClick={close}>×</button></div><div className="drawer-summary"><div><small>Planejado</small><b>{currency(d.adjusted_value??d.revised_value??d.original_value)}</b></div><div><small>Executado</small><b>{currency(d.executed_value)}</b></div><div><small>Data desejada</small><b>{date(d.desired_date)}</b></div></div><section><h3>Situação e risco</h3><div className="inline-tags"><Status value={d.execution_status}/><Risk risk={d.risk}/></div><ul className="reasons">{d.risk.reasons.map(r=><li key={r}>{r}</li>)}</ul></section><section><h3>Retroplanejamento</h3>{plan?.milestones.map(m=><div className="milestone" key={m.name}><i/><span>{m.name}<small>{date(m.date)}</small></span></div>)}<p className="fineprint">{plan?.non_normative_notice}</p></section><section><h3>Interoperabilidade</h3><div className="readiness-row"><span>PNCP</span><b className={pncp?.valid?'ok':'pending'}>{pncp?.valid?'Payload válido':'Pendências'}</b></div><div className="readiness-row"><span>Publicação automática</span><b className="blocked">Bloqueada</b></div><div className="readiness-row"><span>SEI!</span><b className={d.sei_process_number?'ok':'pending'}>{d.sei_process_number||'Não vinculado'}</b></div>{pncp?.errors.map(e=><p className="fineprint" key={e}>{e}</p>)}</section><section><h3>Histórico preservado</h3>{versions.map(v=><div className="history" key={`${v.version}-${v.created_at}`}><b>v{v.version}</b><span>{labels[v.reason]||v.reason}<small>{new Date(v.created_at).toLocaleString('pt-BR')}</small></span></div>)}</section></aside></div>}
function Metric({label,value,hint,tone,progress}:{label:string;value:string;hint:string;tone:string;progress?:number}){return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong>{progress!==undefined&&<div className="progress"><i style={{width:`${Math.min(progress,100)}%`}}/></div>}<small>{hint}</small></article>}
function Signal({value,label}:{value:number;label:string}){return <div><strong>{value}</strong><span>{label}</span></div>}
function Status({value}:{value:string}){return <span className={`status ${value}`}>{labels[value]||value}</span>}
function Risk({risk}:{risk:Risk}){return <span className={`risk ${risk.level}`}><i/>{risk.label}</span>}
function Check({text}:{text:string}){return <div className="check"><i>✓</i>{text}</div>}
function Nav({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:string;children:string}){return <button className={active?'active':''} onClick={onClick}><i>{icon}</i>{children}</button>}
function Alert({kind,text,close}:{kind:string;text:string;close:()=>void}){return <div className={`alert ${kind}`}><span>{text}</span><button onClick={close}>×</button></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay"><div className="modal"><div className="panel-title"><h2>{title}</h2><button className="icon-button" onClick={close}>×</button></div>{children}</div></div>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)
